name: Create Release

on:
  workflow_call:
    outputs:
      upload_asset_url:
        description: "URL to upload release assets"
        value: ${{ steps.create_release.outputs.upload_url }}  # Reference the step output directly

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          
      - name: Debug Outputs
        id: debug_outputs
        run: |
          echo "Upload URL: ${{ steps.create_release.outputs.upload_url }}"
