name: Create Release

on:
  workflow_call:
    outputs:
      upload_asset_url:
        description: "Url to upload release assets"
        value: ${{ jobs.create-release.outputs.output1 }}

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false