name: Main Build Workflow

on:
  push:
    tags:
      - v*
    branches:
      - feat/github-actions-compose-build
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    uses: ./.github/workflows/create-release.yml

  build-android:
    needs: create-release
    permissions: write-all
    uses: ./.github/workflows/build-android.yml

  build-windows:
    needs: create-release
    permissions: write-all
    uses: ./.github/workflows/build-windows.yml

  build-macos:
    needs: create-release
    permissions: write-all
    uses: ./.github/workflows/build-macos.yml