name: Main Build Workflow

on:
  push:
    tags:
      - v*
    branches:
      - feat/github-actions-compose-build
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_APPLICATION_ID: ${{ secrets.FIREBASE_APPLICATION_ID }}
  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
  

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml

  build-android:
    needs: create-release
    uses: ./.github/workflows/build-android.yml

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml

  build-macos:
    needs: create-release
    uses: ./.github/workflows/build-macos.yml