name: Main Build Workflow

on:
  push:
    tags:
      - v*
    branches:
      - feat/github-actions-compose-build
  workflow_dispatch:

permissions: write-all

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml
    outputs:
      upload_asset_url: ${{ steps.create_release.outputs.upload_asset_url }}

  #build-android:
  #  needs: create-release
  #  uses: ./.github/workflows/build-android.yml

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml
    with:
      upload_asset_url: ${{ needs.create-release.outputs.upload_asset_url }}

  #build-macos:
  #  needs: create-release
  #  uses: ./.github/workflows/build-macos.yml