name: Main Build Workflow

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions: write-all

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml


  #build-android:
  #  needs: create-release
  #  uses: ./.github/workflows/build-android.yml

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml
    with:
      asset_url: ${{ needs.create-release.outputs.upload_asset_url }}
    secrets: inherit

  build-macos:
    needs: create-release
    uses: ./.github/workflows/build-macos.yml
    with:
      asset_url: ${{ needs.create-release.outputs.upload_asset_url }}
    secrets: inherit